// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: rgbx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RgbxAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ty int32 `protobuf:"varint,1,opt,name=ty,proto3" json:"ty,omitempty"`
	// Types that are assignable to Value:
	//	*RgbxAction_Mint
	//	*RgbxAction_Transfer
	//	*RgbxAction_Confirm
	//	*RgbxAction_CommitDKG
	//	*RgbxAction_Deposit
	//	*RgbxAction_Withdraw
	Value isRgbxAction_Value `protobuf_oneof:"value"`
}

func (x *RgbxAction) Reset() {
	*x = RgbxAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RgbxAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgbxAction) ProtoMessage() {}

func (x *RgbxAction) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgbxAction.ProtoReflect.Descriptor instead.
func (*RgbxAction) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{0}
}

func (x *RgbxAction) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

func (m *RgbxAction) GetValue() isRgbxAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *RgbxAction) GetMint() *MintAsset {
	if x, ok := x.GetValue().(*RgbxAction_Mint); ok {
		return x.Mint
	}
	return nil
}

func (x *RgbxAction) GetTransfer() *TransferAsset {
	if x, ok := x.GetValue().(*RgbxAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

func (x *RgbxAction) GetConfirm() *ConfirmTx {
	if x, ok := x.GetValue().(*RgbxAction_Confirm); ok {
		return x.Confirm
	}
	return nil
}

func (x *RgbxAction) GetCommitDKG() *CommitDKG {
	if x, ok := x.GetValue().(*RgbxAction_CommitDKG); ok {
		return x.CommitDKG
	}
	return nil
}

func (x *RgbxAction) GetDeposit() *DepositAsset {
	if x, ok := x.GetValue().(*RgbxAction_Deposit); ok {
		return x.Deposit
	}
	return nil
}

func (x *RgbxAction) GetWithdraw() *WithdrawAsset {
	if x, ok := x.GetValue().(*RgbxAction_Withdraw); ok {
		return x.Withdraw
	}
	return nil
}

type isRgbxAction_Value interface {
	isRgbxAction_Value()
}

type RgbxAction_Mint struct {
	Mint *MintAsset `protobuf:"bytes,2,opt,name=mint,proto3,oneof"`
}

type RgbxAction_Transfer struct {
	Transfer *TransferAsset `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

type RgbxAction_Confirm struct {
	Confirm *ConfirmTx `protobuf:"bytes,4,opt,name=confirm,proto3,oneof"`
}

type RgbxAction_CommitDKG struct {
	CommitDKG *CommitDKG `protobuf:"bytes,5,opt,name=commitDKG,proto3,oneof"`
}

type RgbxAction_Deposit struct {
	Deposit *DepositAsset `protobuf:"bytes,6,opt,name=deposit,proto3,oneof"`
}

type RgbxAction_Withdraw struct {
	Withdraw *WithdrawAsset `protobuf:"bytes,7,opt,name=withdraw,proto3,oneof"`
}

func (*RgbxAction_Mint) isRgbxAction_Value() {}

func (*RgbxAction_Transfer) isRgbxAction_Value() {}

func (*RgbxAction_Confirm) isRgbxAction_Value() {}

func (*RgbxAction_CommitDKG) isRgbxAction_Value() {}

func (*RgbxAction_Deposit) isRgbxAction_Value() {}

func (*RgbxAction_Withdraw) isRgbxAction_Value() {}

type RgbxAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type             uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Precision        uint32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	TotalAmount      int64  `protobuf:"varint,3,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Symbol           string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MetaHash         []byte `protobuf:"bytes,5,opt,name=metaHash,proto3" json:"metaHash,omitempty"`
	GenesisBtcTxHash string `protobuf:"bytes,6,opt,name=genesisBtcTxHash,proto3" json:"genesisBtcTxHash,omitempty"`
	Owner            string `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RgbxAsset) Reset() {
	*x = RgbxAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RgbxAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgbxAsset) ProtoMessage() {}

func (x *RgbxAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgbxAsset.ProtoReflect.Descriptor instead.
func (*RgbxAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{1}
}

func (x *RgbxAsset) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RgbxAsset) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *RgbxAsset) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *RgbxAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RgbxAsset) GetMetaHash() []byte {
	if x != nil {
		return x.MetaHash
	}
	return nil
}

func (x *RgbxAsset) GetGenesisBtcTxHash() string {
	if x != nil {
		return x.GenesisBtcTxHash
	}
	return ""
}

func (x *RgbxAsset) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type MintAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Precision   uint32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	TotalAmount int64  `protobuf:"varint,3,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Symbol      string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MetaHash    []byte `protobuf:"bytes,5,opt,name=metaHash,proto3" json:"metaHash,omitempty"`
	// represents the outpoint of the transaction's
	// input that resulted in the creation of the asset.
	GenesisOut *OutPoint `protobuf:"bytes,6,opt,name=genesisOut,proto3" json:"genesisOut,omitempty"`
}

func (x *MintAsset) Reset() {
	*x = MintAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintAsset) ProtoMessage() {}

func (x *MintAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintAsset.ProtoReflect.Descriptor instead.
func (*MintAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{2}
}

func (x *MintAsset) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MintAsset) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *MintAsset) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MintAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MintAsset) GetMetaHash() []byte {
	if x != nil {
		return x.MetaHash
	}
	return nil
}

func (x *MintAsset) GetGenesisOut() *OutPoint {
	if x != nil {
		return x.GenesisOut
	}
	return nil
}

type OutPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash     string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index    uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	PkScript []byte `protobuf:"bytes,3,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
}

func (x *OutPoint) Reset() {
	*x = OutPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutPoint) ProtoMessage() {}

func (x *OutPoint) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutPoint.ProtoReflect.Descriptor instead.
func (*OutPoint) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{3}
}

func (x *OutPoint) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *OutPoint) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OutPoint) GetPkScript() []byte {
	if x != nil {
		return x.PkScript
	}
	return nil
}

type UtxoSpendingProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpendingInputIdx uint32 `protobuf:"varint,1,opt,name=spendingInputIdx,proto3" json:"spendingInputIdx,omitempty"`
	OpRetOutputIdx   int32  `protobuf:"varint,2,opt,name=opRetOutputIdx,proto3" json:"opRetOutputIdx,omitempty"`
}

func (x *UtxoSpendingProof) Reset() {
	*x = UtxoSpendingProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UtxoSpendingProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoSpendingProof) ProtoMessage() {}

func (x *UtxoSpendingProof) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoSpendingProof.ProtoReflect.Descriptor instead.
func (*UtxoSpendingProof) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{4}
}

func (x *UtxoSpendingProof) GetSpendingInputIdx() uint32 {
	if x != nil {
		return x.SpendingInputIdx
	}
	return 0
}

func (x *UtxoSpendingProof) GetOpRetOutputIdx() int32 {
	if x != nil {
		return x.OpRetOutputIdx
	}
	return 0
}

type TransferAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol           string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount           int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	FromUtxo         string `protobuf:"bytes,3,opt,name=fromUtxo,proto3" json:"fromUtxo,omitempty"`
	To               string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	ChangeAddr       string `protobuf:"bytes,5,opt,name=changeAddr,proto3" json:"changeAddr,omitempty"`
	FromUtxoPkScript []byte `protobuf:"bytes,6,opt,name=fromUtxoPkScript,proto3" json:"fromUtxoPkScript,omitempty"`
}

func (x *TransferAsset) Reset() {
	*x = TransferAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAsset) ProtoMessage() {}

func (x *TransferAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAsset.ProtoReflect.Descriptor instead.
func (*TransferAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{5}
}

func (x *TransferAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TransferAsset) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferAsset) GetFromUtxo() string {
	if x != nil {
		return x.FromUtxo
	}
	return ""
}

func (x *TransferAsset) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferAsset) GetChangeAddr() string {
	if x != nil {
		return x.ChangeAddr
	}
	return ""
}

func (x *TransferAsset) GetFromUtxoPkScript() []byte {
	if x != nil {
		return x.FromUtxoPkScript
	}
	return nil
}

type ConfirmTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType           int32              `protobuf:"varint,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	ConfirmedBlockHeight int64              `protobuf:"varint,2,opt,name=confirmedBlockHeight,proto3" json:"confirmedBlockHeight,omitempty"`
	TxBlockHeight        int64              `protobuf:"varint,3,opt,name=txBlockHeight,proto3" json:"txBlockHeight,omitempty"`
	TxIndex              int64              `protobuf:"varint,4,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	TxHash               []byte             `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Timeout              bool               `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	UtxoProof            *UtxoSpendingProof `protobuf:"bytes,7,opt,name=utxoProof,proto3" json:"utxoProof,omitempty"`
	BtcTxProof           *BtcTxProof        `protobuf:"bytes,8,opt,name=btcTxProof,proto3" json:"btcTxProof,omitempty"`
}

func (x *ConfirmTx) Reset() {
	*x = ConfirmTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTx) ProtoMessage() {}

func (x *ConfirmTx) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTx.ProtoReflect.Descriptor instead.
func (*ConfirmTx) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmTx) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *ConfirmTx) GetConfirmedBlockHeight() int64 {
	if x != nil {
		return x.ConfirmedBlockHeight
	}
	return 0
}

func (x *ConfirmTx) GetTxBlockHeight() int64 {
	if x != nil {
		return x.TxBlockHeight
	}
	return 0
}

func (x *ConfirmTx) GetTxIndex() int64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *ConfirmTx) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ConfirmTx) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

func (x *ConfirmTx) GetUtxoProof() *UtxoSpendingProof {
	if x != nil {
		return x.UtxoProof
	}
	return nil
}

func (x *ConfirmTx) GetBtcTxProof() *BtcTxProof {
	if x != nil {
		return x.BtcTxProof
	}
	return nil
}

type BtcTxProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight uint64   `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	TxIndex     uint32   `protobuf:"varint,2,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	BlockHash   string   `protobuf:"bytes,3,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxData      []byte   `protobuf:"bytes,4,opt,name=txData,proto3" json:"txData,omitempty"`
	MerkleProof [][]byte `protobuf:"bytes,5,rep,name=merkleProof,proto3" json:"merkleProof,omitempty"`
}

func (x *BtcTxProof) Reset() {
	*x = BtcTxProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcTxProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcTxProof) ProtoMessage() {}

func (x *BtcTxProof) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcTxProof.ProtoReflect.Descriptor instead.
func (*BtcTxProof) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{7}
}

func (x *BtcTxProof) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *BtcTxProof) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *BtcTxProof) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BtcTxProof) GetTxData() []byte {
	if x != nil {
		return x.TxData
	}
	return nil
}

func (x *BtcTxProof) GetMerkleProof() [][]byte {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

type CommitDKG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string `protobuf:"bytes,1,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	DkgAddress  string `protobuf:"bytes,2,opt,name=dkgAddress,proto3" json:"dkgAddress,omitempty"`
	PkScript    []byte `protobuf:"bytes,3,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
	// TSS 组公钥（压缩 secp256k1），RGB20 分支 checkCommitDKG 校验 hash160(pubkey)==pkScript[2:]（BL-1）
	Pubkey []byte `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *CommitDKG) Reset() {
	*x = CommitDKG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitDKG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDKG) ProtoMessage() {}

func (x *CommitDKG) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDKG.ProtoReflect.Descriptor instead.
func (*CommitDKG) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{8}
}

func (x *CommitDKG) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *CommitDKG) GetDkgAddress() string {
	if x != nil {
		return x.DkgAddress
	}
	return ""
}

func (x *CommitDKG) GetPkScript() []byte {
	if x != nil {
		return x.PkScript
	}
	return nil
}

func (x *CommitDKG) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type DepositAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount         int64       `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	DepositAddress string      `protobuf:"bytes,2,opt,name=depositAddress,proto3" json:"depositAddress,omitempty"`
	AssetSymbol    string      `protobuf:"bytes,3,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	TxProof        *BtcTxProof `protobuf:"bytes,4,opt,name=txProof,proto3" json:"txProof,omitempty"`
	// RGB20 分支的 TSS 阈值签名（DER，对 C=sha256(types.Encode(DepositAsset{thresholdSig:nil}))）
	ThresholdSig []byte `protobuf:"bytes,5,opt,name=thresholdSig,proto3" json:"thresholdSig,omitempty"`
}

func (x *DepositAsset) Reset() {
	*x = DepositAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAsset) ProtoMessage() {}

func (x *DepositAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAsset.ProtoReflect.Descriptor instead.
func (*DepositAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{9}
}

func (x *DepositAsset) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositAsset) GetDepositAddress() string {
	if x != nil {
		return x.DepositAddress
	}
	return ""
}

func (x *DepositAsset) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *DepositAsset) GetTxProof() *BtcTxProof {
	if x != nil {
		return x.TxProof
	}
	return nil
}

func (x *DepositAsset) GetThresholdSig() []byte {
	if x != nil {
		return x.ThresholdSig
	}
	return nil
}

type WithdrawAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount          int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeRate         int64  `protobuf:"varint,2,opt,name=feeRate,proto3" json:"feeRate,omitempty"`
	DestinationAddr string `protobuf:"bytes,3,opt,name=destinationAddr,proto3" json:"destinationAddr,omitempty"`
	AssetSymbol     string `protobuf:"bytes,4,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
}

func (x *WithdrawAsset) Reset() {
	*x = WithdrawAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawAsset) ProtoMessage() {}

func (x *WithdrawAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawAsset.ProtoReflect.Descriptor instead.
func (*WithdrawAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawAsset) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawAsset) GetFeeRate() int64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *WithdrawAsset) GetDestinationAddr() string {
	if x != nil {
		return x.DestinationAddr
	}
	return ""
}

func (x *WithdrawAsset) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

type CrossChainInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol   string `protobuf:"bytes,1,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	WrappedSymbol string `protobuf:"bytes,2,opt,name=wrappedSymbol,proto3" json:"wrappedSymbol,omitempty"`
	TssAddress    string `protobuf:"bytes,3,opt,name=tssAddress,proto3" json:"tssAddress,omitempty"`
	PkScript      []byte `protobuf:"bytes,4,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
	// TSS 组公钥（压缩 secp256k1），RGB20 分支验 thresholdSig 用（BL-1）
	Pubkey []byte `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *CrossChainInfo) Reset() {
	*x = CrossChainInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossChainInfo) ProtoMessage() {}

func (x *CrossChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossChainInfo.ProtoReflect.Descriptor instead.
func (*CrossChainInfo) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{11}
}

func (x *CrossChainInfo) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *CrossChainInfo) GetWrappedSymbol() string {
	if x != nil {
		return x.WrappedSymbol
	}
	return ""
}

func (x *CrossChainInfo) GetTssAddress() string {
	if x != nil {
		return x.TssAddress
	}
	return ""
}

func (x *CrossChainInfo) GetPkScript() []byte {
	if x != nil {
		return x.PkScript
	}
	return nil
}

func (x *CrossChainInfo) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type PendingTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType    int32     `protobuf:"varint,1,opt,name=actionType,proto3" json:"actionType,omitempty"`
	Timestamp     int64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxBlockHeight int64     `protobuf:"varint,3,opt,name=txBlockHeight,proto3" json:"txBlockHeight,omitempty"`
	TxIndex       int64     `protobuf:"varint,4,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	Amount        int64     `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeRate       int64     `protobuf:"varint,6,opt,name=feeRate,proto3" json:"feeRate,omitempty"`
	TxHash        []byte    `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Utxo          *OutPoint `protobuf:"bytes,8,opt,name=utxo,proto3" json:"utxo,omitempty"`
	FromAddress   string    `protobuf:"bytes,9,opt,name=fromAddress,proto3" json:"fromAddress,omitempty"`
	AssetSymbol   string    `protobuf:"bytes,10,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	TargetAddress string    `protobuf:"bytes,11,opt,name=targetAddress,proto3" json:"targetAddress,omitempty"`
	Confirmed     bool      `protobuf:"varint,12,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
}

func (x *PendingTx) Reset() {
	*x = PendingTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTx) ProtoMessage() {}

func (x *PendingTx) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTx.ProtoReflect.Descriptor instead.
func (*PendingTx) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{12}
}

func (x *PendingTx) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *PendingTx) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PendingTx) GetTxBlockHeight() int64 {
	if x != nil {
		return x.TxBlockHeight
	}
	return 0
}

func (x *PendingTx) GetTxIndex() int64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *PendingTx) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PendingTx) GetFeeRate() int64 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

func (x *PendingTx) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *PendingTx) GetUtxo() *OutPoint {
	if x != nil {
		return x.Utxo
	}
	return nil
}

func (x *PendingTx) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *PendingTx) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *PendingTx) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *PendingTx) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type PendingTxs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingList []*PendingTx `protobuf:"bytes,1,rep,name=pendingList,proto3" json:"pendingList,omitempty"`
}

func (x *PendingTxs) Reset() {
	*x = PendingTxs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingTxs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTxs) ProtoMessage() {}

func (x *PendingTxs) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTxs.ProtoReflect.Descriptor instead.
func (*PendingTxs) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{13}
}

func (x *PendingTxs) GetPendingList() []*PendingTx {
	if x != nil {
		return x.PendingList
	}
	return nil
}

type Utxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutPoint string `protobuf:"bytes,1,opt,name=outPoint,proto3" json:"outPoint,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PkScript []byte `protobuf:"bytes,3,opt,name=pkScript,proto3" json:"pkScript,omitempty"`
}

func (x *Utxo) Reset() {
	*x = Utxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Utxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utxo) ProtoMessage() {}

func (x *Utxo) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utxo.ProtoReflect.Descriptor instead.
func (*Utxo) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{14}
}

func (x *Utxo) GetOutPoint() string {
	if x != nil {
		return x.OutPoint
	}
	return ""
}

func (x *Utxo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Utxo) GetPkScript() []byte {
	if x != nil {
		return x.PkScript
	}
	return nil
}

type ReqListPendingTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartHeight int64 `protobuf:"varint,1,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	StartIndex  int64 `protobuf:"varint,2,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	Count       int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	EndHeight   int64 `protobuf:"varint,4,opt,name=endHeight,proto3" json:"endHeight,omitempty"`
}

func (x *ReqListPendingTx) Reset() {
	*x = ReqListPendingTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqListPendingTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListPendingTx) ProtoMessage() {}

func (x *ReqListPendingTx) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListPendingTx.ProtoReflect.Descriptor instead.
func (*ReqListPendingTx) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{15}
}

func (x *ReqListPendingTx) GetStartHeight() int64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *ReqListPendingTx) GetStartIndex() int64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *ReqListPendingTx) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqListPendingTx) GetEndHeight() int64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

type ReqGetPendingTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index  int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *ReqGetPendingTx) Reset() {
	*x = ReqGetPendingTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetPendingTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetPendingTx) ProtoMessage() {}

func (x *ReqGetPendingTx) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetPendingTx.ProtoReflect.Descriptor instead.
func (*ReqGetPendingTx) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{16}
}

func (x *ReqGetPendingTx) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ReqGetPendingTx) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type BtcCommitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol []byte `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Action   uint32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload  []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *BtcCommitment) Reset() {
	*x = BtcCommitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BtcCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BtcCommitment) ProtoMessage() {}

func (x *BtcCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BtcCommitment.ProtoReflect.Descriptor instead.
func (*BtcCommitment) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{17}
}

func (x *BtcCommitment) GetProtocol() []byte {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *BtcCommitment) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *BtcCommitment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type TxBlockIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight int64 `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	TxIndex     int64 `protobuf:"varint,2,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
}

func (x *TxBlockIndex) Reset() {
	*x = TxBlockIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxBlockIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBlockIndex) ProtoMessage() {}

func (x *TxBlockIndex) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBlockIndex.ProtoReflect.Descriptor instead.
func (*TxBlockIndex) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{18}
}

func (x *TxBlockIndex) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *TxBlockIndex) GetTxIndex() int64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

type TxBlockIndexList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockIndexList []*TxBlockIndex `protobuf:"bytes,1,rep,name=blockIndexList,proto3" json:"blockIndexList,omitempty"`
}

func (x *TxBlockIndexList) Reset() {
	*x = TxBlockIndexList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxBlockIndexList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxBlockIndexList) ProtoMessage() {}

func (x *TxBlockIndexList) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxBlockIndexList.ProtoReflect.Descriptor instead.
func (*TxBlockIndexList) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{19}
}

func (x *TxBlockIndexList) GetBlockIndexList() []*TxBlockIndex {
	if x != nil {
		return x.BlockIndexList
	}
	return nil
}

// ================= 全局 operationId + 铸造台账（S2）=================
//
// 每笔充值（铸造）与提现（销毁）都分配一个 32 字节全局 operationId，链上留下一条**不可变**记录
// （operationRecord），并维护每 symbol 的**单调**供应量计数（operationSupply）。
// operationId 不是外部输入，而是由链上已校验的数据**确定性派生**（见 types/operation.go）：
//   - 充值：sha256("rgbx:opid:v1:mint:" | symbol | btc txid | 充值地址 | 金额)；
//   - 提现：sha256("rgbx:opid:v1:burn:" | symbol | burn 的 chain33 交易哈希)。
//
// 于是"同一个 operationId" ⟺ "同一笔操作"，派生式 id 无法被伪造、无法被顶替，也不需要
// 在交易里额外携带字段（P2WSH 充值路径下没有 OP_RETURN 可承载）。
//
// 提现结算时以该台账为判据：必须存在对应的 burn 记录、金额与 payload 逐项一致，
// 且**待提取的额度不超过台账里"已铸造 − 已销毁"** —— 即每个离开桥的单位都必须有一条
// 充值铸造记录，而不是靠对某个地址的余额求和来推断。
type OperationRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// operationId 32 字节全局操作 id（派生式，见上）
	OperationId []byte `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	// kind 1=铸造（充值） 2=销毁（提现）
	Kind int32 `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// symbol 归一化后的跨链资产符号（如 "XBTC" / "XRGB20_USDT"）
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// network 该操作所属的源/目标网络标识（由 symbol 确定性导出，不读节点本地配置）
	Network string `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// amount 资产最小单位金额（充值=实际到账额；提现=锁定额）
	Amount int64 `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// owner 充值归属地址 / 提现发起地址
	Owner string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// btcTxID 充值：付款那笔 BTC 交易的规范 txid（32 字节）；提现为空
	BtcTxID []byte `protobuf:"bytes,7,opt,name=btcTxID,proto3" json:"btcTxID,omitempty"`
	// chain33TxHash 该操作所在的 chain33 交易哈希（充值=上链的充值交易；提现=burn 交易）
	Chain33TxHash []byte `protobuf:"bytes,8,opt,name=chain33TxHash,proto3" json:"chain33TxHash,omitempty"`
	// height / timestamp 该操作所在区块的高度与时间
	Height    int64 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp int64 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// settled 仅由查询侧补算（提现=是否已结算放款；充值=已铸造，恒 true），**不入库**
	Settled bool `protobuf:"varint,11,opt,name=settled,proto3" json:"settled,omitempty"`
}

func (x *OperationRecord) Reset() {
	*x = OperationRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRecord) ProtoMessage() {}

func (x *OperationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRecord.ProtoReflect.Descriptor instead.
func (*OperationRecord) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{20}
}

func (x *OperationRecord) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *OperationRecord) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *OperationRecord) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OperationRecord) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *OperationRecord) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OperationRecord) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *OperationRecord) GetBtcTxID() []byte {
	if x != nil {
		return x.BtcTxID
	}
	return nil
}

func (x *OperationRecord) GetChain33TxHash() []byte {
	if x != nil {
		return x.Chain33TxHash
	}
	return nil
}

func (x *OperationRecord) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OperationRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OperationRecord) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

type OperationSupply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// minted / burned 累计铸造 / 累计销毁（资产最小单位）；minted - burned 即"桥仍欠的额度"
	Minted int64 `protobuf:"varint,3,opt,name=minted,proto3" json:"minted,omitempty"`
	Burned int64 `protobuf:"varint,4,opt,name=burned,proto3" json:"burned,omitempty"`
	// nextMintIndex / nextBurnIndex 下一个索引下标（生成本 symbol 的操作列表用）
	NextMintIndex int64 `protobuf:"varint,5,opt,name=nextMintIndex,proto3" json:"nextMintIndex,omitempty"`
	NextBurnIndex int64 `protobuf:"varint,6,opt,name=nextBurnIndex,proto3" json:"nextBurnIndex,omitempty"`
}

func (x *OperationSupply) Reset() {
	*x = OperationSupply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationSupply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationSupply) ProtoMessage() {}

func (x *OperationSupply) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationSupply.ProtoReflect.Descriptor instead.
func (*OperationSupply) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{21}
}

func (x *OperationSupply) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OperationSupply) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *OperationSupply) GetMinted() int64 {
	if x != nil {
		return x.Minted
	}
	return 0
}

func (x *OperationSupply) GetBurned() int64 {
	if x != nil {
		return x.Burned
	}
	return 0
}

func (x *OperationSupply) GetNextMintIndex() int64 {
	if x != nil {
		return x.NextMintIndex
	}
	return 0
}

func (x *OperationSupply) GetNextBurnIndex() int64 {
	if x != nil {
		return x.NextBurnIndex
	}
	return 0
}

type OperationRecords struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*OperationRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// nextIndex 下一页的起始下标（本页取满 count 条时才有意义；否则为 0）
	NextIndex int64 `protobuf:"varint,2,opt,name=nextIndex,proto3" json:"nextIndex,omitempty"`
}

func (x *OperationRecords) Reset() {
	*x = OperationRecords{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRecords) ProtoMessage() {}

func (x *OperationRecords) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRecords.ProtoReflect.Descriptor instead.
func (*OperationRecords) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{22}
}

func (x *OperationRecords) GetRecords() []*OperationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *OperationRecords) GetNextIndex() int64 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

type ReqGetOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationId []byte `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
}

func (x *ReqGetOperation) Reset() {
	*x = ReqGetOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetOperation) ProtoMessage() {}

func (x *ReqGetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetOperation.ProtoReflect.Descriptor instead.
func (*ReqGetOperation) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{23}
}

func (x *ReqGetOperation) GetOperationId() []byte {
	if x != nil {
		return x.OperationId
	}
	return nil
}

type ReqListOperations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string `protobuf:"bytes,1,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	// kind 1=铸造 2=销毁（必须显式指定：两类操作各自一条索引）
	Kind int32 `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// start 起始下标（首次查询填 0；后续用上一次返回的 nextIndex 续查）
	Start int64 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReqListOperations) Reset() {
	*x = ReqListOperations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqListOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqListOperations) ProtoMessage() {}

func (x *ReqListOperations) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqListOperations.ProtoReflect.Descriptor instead.
func (*ReqListOperations) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{24}
}

func (x *ReqListOperations) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ReqListOperations) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *ReqListOperations) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *ReqListOperations) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_rgbx_proto protoreflect.FileDescriptor

var file_rgbx_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x67, 0x62, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x22, 0xc6, 0x02, 0x0a, 0x0a, 0x52, 0x67, 0x62, 0x78, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x74, 0x79, 0x12, 0x26, 0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6d, 0x69, 0x6e, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x69, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x54,
	0x78, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x30, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x4b, 0x47, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x4b,
	0x47, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x4b, 0x47, 0x12, 0x2f,
	0x0a, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12,
	0x32, 0x0a, 0x08, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd5, 0x01, 0x0a,
	0x09, 0x72, 0x67, 0x62, 0x78, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x74, 0x63,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x67, 0x65,
	0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x74, 0x63, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x22, 0xc4, 0x01, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2f, 0x0a, 0x0a, 0x67, 0x65,
	0x6e, 0x65, 0x73, 0x69, 0x73, 0x4f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x0a, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x50, 0x0a, 0x08, 0x6f,
	0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x67, 0x0a,
	0x11, 0x75, 0x74, 0x78, 0x6f, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x49, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x70,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x64, 0x78, 0x12, 0x26,
	0x0a, 0x0e, 0x6f, 0x70, 0x52, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x64, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x70, 0x52, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x49, 0x64, 0x78, 0x22, 0xb7, 0x01, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x55, 0x74, 0x78, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x55, 0x74, 0x78, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64,
	0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x74, 0x78, 0x6f,
	0x50, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10,
	0x66, 0x72, 0x6f, 0x6d, 0x55, 0x74, 0x78, 0x6f, 0x50, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x22, 0xbc, 0x02, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x54, 0x78, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32,
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x78, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x75, 0x74, 0x78, 0x6f, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x75, 0x74, 0x78, 0x6f, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x52, 0x09, 0x75, 0x74, 0x78, 0x6f, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x31, 0x0a, 0x0a,
	0x62, 0x74, 0x63, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x62, 0x74, 0x63, 0x54, 0x78, 0x50, 0x72,
	0x6f, 0x6f, 0x66, 0x52, 0x0a, 0x62, 0x74, 0x63, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22,
	0xa0, 0x01, 0x0a, 0x0a, 0x62, 0x74, 0x63, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x20,
	0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x44, 0x4b, 0x47,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6b, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6b, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0xc1, 0x01, 0x0a, 0x0c, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x2b, 0x0a, 0x07, 0x74, 0x78, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x62, 0x74, 0x63, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x07, 0x74,
	0x78, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x53, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x53, 0x69, 0x67, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x77,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x63,
	0x72, 0x6f, 0x73, 0x73, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x24, 0x0a, 0x0d, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x73, 0x73, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x80, 0x03, 0x0a, 0x09, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x78,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x78,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x23, 0x0a, 0x04, 0x75, 0x74, 0x78, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04,
	0x75, 0x74, 0x78, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x22, 0x40, 0x0a, 0x0a,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x78, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x78, 0x52, 0x0b, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x56,
	0x0a, 0x04, 0x75, 0x74, 0x78, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6b,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6b,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x54, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x5d, 0x0a, 0x0d, 0x62, 0x74, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x4a, 0x0a, 0x0c, 0x74, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x78, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x4f, 0x0a,
	0x10, 0x74, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x74, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x0e,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xb7,
	0x02, 0x0a, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x74, 0x63, 0x54,
	0x78, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x62, 0x74, 0x63, 0x54, 0x78,
	0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x33, 0x33, 0x54, 0x78, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x33, 0x33, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x22, 0xbf, 0x01, 0x0a, 0x0f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6d, 0x69, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x72, 0x6e, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x75, 0x72, 0x6e, 0x65, 0x64, 0x12, 0x24,
	0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x4d, 0x69, 0x6e, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x42, 0x75, 0x72, 0x6e,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6e, 0x65, 0x78,
	0x74, 0x42, 0x75, 0x72, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x62, 0x0a, 0x10, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x30,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x33,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x06, 0x0a, 0x04, 0x72, 0x67,
	0x62, 0x78, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rgbx_proto_rawDescOnce sync.Once
	file_rgbx_proto_rawDescData = file_rgbx_proto_rawDesc
)

func file_rgbx_proto_rawDescGZIP() []byte {
	file_rgbx_proto_rawDescOnce.Do(func() {
		file_rgbx_proto_rawDescData = protoimpl.X.CompressGZIP(file_rgbx_proto_rawDescData)
	})
	return file_rgbx_proto_rawDescData
}

var file_rgbx_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rgbx_proto_goTypes = []interface{}{
	(*RgbxAction)(nil),        // 0: types.RgbxAction
	(*RgbxAsset)(nil),         // 1: types.rgbxAsset
	(*MintAsset)(nil),         // 2: types.mintAsset
	(*OutPoint)(nil),          // 3: types.outPoint
	(*UtxoSpendingProof)(nil), // 4: types.utxoSpendingProof
	(*TransferAsset)(nil),     // 5: types.transferAsset
	(*ConfirmTx)(nil),         // 6: types.confirmTx
	(*BtcTxProof)(nil),        // 7: types.btcTxProof
	(*CommitDKG)(nil),         // 8: types.commitDKG
	(*DepositAsset)(nil),      // 9: types.depositAsset
	(*WithdrawAsset)(nil),     // 10: types.withdrawAsset
	(*CrossChainInfo)(nil),    // 11: types.crossChainInfo
	(*PendingTx)(nil),         // 12: types.pendingTx
	(*PendingTxs)(nil),        // 13: types.pendingTxs
	(*Utxo)(nil),              // 14: types.utxo
	(*ReqListPendingTx)(nil),  // 15: types.ReqListPendingTx
	(*ReqGetPendingTx)(nil),   // 16: types.ReqGetPendingTx
	(*BtcCommitment)(nil),     // 17: types.btcCommitment
	(*TxBlockIndex)(nil),      // 18: types.txBlockIndex
	(*TxBlockIndexList)(nil),  // 19: types.txBlockIndexList
	(*OperationRecord)(nil),   // 20: types.operationRecord
	(*OperationSupply)(nil),   // 21: types.operationSupply
	(*OperationRecords)(nil),  // 22: types.operationRecords
	(*ReqGetOperation)(nil),   // 23: types.ReqGetOperation
	(*ReqListOperations)(nil), // 24: types.ReqListOperations
}
var file_rgbx_proto_depIdxs = []int32{
	2,  // 0: types.RgbxAction.mint:type_name -> types.mintAsset
	5,  // 1: types.RgbxAction.transfer:type_name -> types.transferAsset
	6,  // 2: types.RgbxAction.confirm:type_name -> types.confirmTx
	8,  // 3: types.RgbxAction.commitDKG:type_name -> types.commitDKG
	9,  // 4: types.RgbxAction.deposit:type_name -> types.depositAsset
	10, // 5: types.RgbxAction.withdraw:type_name -> types.withdrawAsset
	3,  // 6: types.mintAsset.genesisOut:type_name -> types.outPoint
	4,  // 7: types.confirmTx.utxoProof:type_name -> types.utxoSpendingProof
	7,  // 8: types.confirmTx.btcTxProof:type_name -> types.btcTxProof
	7,  // 9: types.depositAsset.txProof:type_name -> types.btcTxProof
	3,  // 10: types.pendingTx.utxo:type_name -> types.outPoint
	12, // 11: types.pendingTxs.pendingList:type_name -> types.pendingTx
	18, // 12: types.txBlockIndexList.blockIndexList:type_name -> types.txBlockIndex
	20, // 13: types.operationRecords.records:type_name -> types.operationRecord
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rgbx_proto_init() }
func file_rgbx_proto_init() {
	if File_rgbx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rgbx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RgbxAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RgbxAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MintAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UtxoSpendingProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcTxProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitDKG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossChainInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingTxs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Utxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqListPendingTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetPendingTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BtcCommitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxBlockIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxBlockIndexList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationSupply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationRecords); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqListOperations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rgbx_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RgbxAction_Mint)(nil),
		(*RgbxAction_Transfer)(nil),
		(*RgbxAction_Confirm)(nil),
		(*RgbxAction_CommitDKG)(nil),
		(*RgbxAction_Deposit)(nil),
		(*RgbxAction_Withdraw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rgbx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rgbx_proto_goTypes,
		DependencyIndexes: file_rgbx_proto_depIdxs,
		MessageInfos:      file_rgbx_proto_msgTypes,
	}.Build()
	File_rgbx_proto = out.File
	file_rgbx_proto_rawDesc = nil
	file_rgbx_proto_goTypes = nil
	file_rgbx_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RgbxClient is the client API for Rgbx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RgbxClient interface {
}

type rgbxClient struct {
	cc grpc.ClientConnInterface
}

func NewRgbxClient(cc grpc.ClientConnInterface) RgbxClient {
	return &rgbxClient{cc}
}

// RgbxServer is the server API for Rgbx service.
type RgbxServer interface {
}

// UnimplementedRgbxServer can be embedded to have forward compatible implementations.
type UnimplementedRgbxServer struct {
}

func RegisterRgbxServer(s *grpc.Server, srv RgbxServer) {
	s.RegisterService(&_Rgbx_serviceDesc, srv)
}

var _Rgbx_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.rgbx",
	HandlerType: (*RgbxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "rgbx.proto",
}
