// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.1
// source: rgbx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RgbxAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ty int32 `protobuf:"varint,1,opt,name=ty,proto3" json:"ty,omitempty"`
	// Types that are assignable to Value:
	//	*RgbxAction_Issue
	//	*RgbxAction_Transfer
	Value isRgbxAction_Value `protobuf_oneof:"value"`
}

func (x *RgbxAction) Reset() {
	*x = RgbxAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RgbxAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgbxAction) ProtoMessage() {}

func (x *RgbxAction) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgbxAction.ProtoReflect.Descriptor instead.
func (*RgbxAction) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{0}
}

func (x *RgbxAction) GetTy() int32 {
	if x != nil {
		return x.Ty
	}
	return 0
}

func (m *RgbxAction) GetValue() isRgbxAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *RgbxAction) GetIssue() *IssueAsset {
	if x, ok := x.GetValue().(*RgbxAction_Issue); ok {
		return x.Issue
	}
	return nil
}

func (x *RgbxAction) GetTransfer() *TransferAsset {
	if x, ok := x.GetValue().(*RgbxAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

type isRgbxAction_Value interface {
	isRgbxAction_Value()
}

type RgbxAction_Issue struct {
	Issue *IssueAsset `protobuf:"bytes,2,opt,name=issue,proto3,oneof"`
}

type RgbxAction_Transfer struct {
	Transfer *TransferAsset `protobuf:"bytes,3,opt,name=transfer,proto3,oneof"`
}

func (*RgbxAction_Issue) isRgbxAction_Value() {}

func (*RgbxAction_Transfer) isRgbxAction_Value() {}

type IssueAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IssueAsset) Reset() {
	*x = IssueAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueAsset) ProtoMessage() {}

func (x *IssueAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueAsset.ProtoReflect.Descriptor instead.
func (*IssueAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{1}
}

type TransferAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransferAsset) Reset() {
	*x = TransferAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgbx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAsset) ProtoMessage() {}

func (x *TransferAsset) ProtoReflect() protoreflect.Message {
	mi := &file_rgbx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAsset.ProtoReflect.Descriptor instead.
func (*TransferAsset) Descriptor() ([]byte, []int) {
	return file_rgbx_proto_rawDescGZIP(), []int{2}
}

var File_rgbx_proto protoreflect.FileDescriptor

var file_rgbx_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x67, 0x62, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x52, 0x67, 0x62, 0x78, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x74, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x69, 0x73, 0x73, 0x75, 0x65, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x05, 0x69, 0x73, 0x73, 0x75, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x32, 0x06, 0x0a, 0x04, 0x72, 0x67, 0x62,
	0x78, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rgbx_proto_rawDescOnce sync.Once
	file_rgbx_proto_rawDescData = file_rgbx_proto_rawDesc
)

func file_rgbx_proto_rawDescGZIP() []byte {
	file_rgbx_proto_rawDescOnce.Do(func() {
		file_rgbx_proto_rawDescData = protoimpl.X.CompressGZIP(file_rgbx_proto_rawDescData)
	})
	return file_rgbx_proto_rawDescData
}

var file_rgbx_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rgbx_proto_goTypes = []interface{}{
	(*RgbxAction)(nil),    // 0: types.RgbxAction
	(*IssueAsset)(nil),    // 1: types.issueAsset
	(*TransferAsset)(nil), // 2: types.transferAsset
}
var file_rgbx_proto_depIdxs = []int32{
	1, // 0: types.RgbxAction.issue:type_name -> types.issueAsset
	2, // 1: types.RgbxAction.transfer:type_name -> types.transferAsset
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rgbx_proto_init() }
func file_rgbx_proto_init() {
	if File_rgbx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rgbx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RgbxAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IssueAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgbx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rgbx_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RgbxAction_Issue)(nil),
		(*RgbxAction_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rgbx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rgbx_proto_goTypes,
		DependencyIndexes: file_rgbx_proto_depIdxs,
		MessageInfos:      file_rgbx_proto_msgTypes,
	}.Build()
	File_rgbx_proto = out.File
	file_rgbx_proto_rawDesc = nil
	file_rgbx_proto_goTypes = nil
	file_rgbx_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RgbxClient is the client API for Rgbx service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RgbxClient interface {
}

type rgbxClient struct {
	cc grpc.ClientConnInterface
}

func NewRgbxClient(cc grpc.ClientConnInterface) RgbxClient {
	return &rgbxClient{cc}
}

// RgbxServer is the server API for Rgbx service.
type RgbxServer interface {
}

// UnimplementedRgbxServer can be embedded to have forward compatible implementations.
type UnimplementedRgbxServer struct {
}

func RegisterRgbxServer(s *grpc.Server, srv RgbxServer) {
	s.RegisterService(&_Rgbx_serviceDesc, srv)
}

var _Rgbx_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.rgbx",
	HandlerType: (*RgbxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "rgbx.proto",
}
