// RGB 侧车 gRPC 契约 —— Go 桥(neutrino) ↔ Rust 侧车
// 共享契约：Rust 侧（tonic）与 Go 侧（protoc）都从本文件生成。
// 修改本契约必须走评审，不得由单侧擅自改动。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: rgb_sidecar.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReceiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol        string   `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Amount             int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // 请求金额（资产最小单位）
	TransportEndpoints []string `protobuf:"bytes,3,rep,name=transport_endpoints,json=transportEndpoints,proto3" json:"transport_endpoints,omitempty"`
	MinConfirmations   uint32   `protobuf:"varint,4,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
}

func (x *CreateReceiveRequest) Reset() {
	*x = CreateReceiveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiveRequest) ProtoMessage() {}

func (x *CreateReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiveRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiveRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReceiveRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *CreateReceiveRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateReceiveRequest) GetTransportEndpoints() []string {
	if x != nil {
		return x.TransportEndpoints
	}
	return nil
}

func (x *CreateReceiveRequest) GetMinConfirmations() uint32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

type ReceiveData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invoice    string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	ReceiveId  string `protobuf:"bytes,2,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	SealScript []byte `protobuf:"bytes,3,opt,name=seal_script,json=sealScript,proto3" json:"seal_script,omitempty"` // 该 receive 对应的 seal 脚本（单脚本钱包下= TSS 脚本）
}

func (x *ReceiveData) Reset() {
	*x = ReceiveData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveData) ProtoMessage() {}

func (x *ReceiveData) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveData.ProtoReflect.Descriptor instead.
func (*ReceiveData) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveData) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

func (x *ReceiveData) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *ReceiveData) GetSealScript() []byte {
	if x != nil {
		return x.SealScript
	}
	return nil
}

type ProvideConsignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consignment   []byte `protobuf:"bytes,1,opt,name=consignment,proto3" json:"consignment,omitempty"`
	ReceiveIdHint string `protobuf:"bytes,2,opt,name=receive_id_hint,json=receiveIdHint,proto3" json:"receive_id_hint,omitempty"` // 可选：缩小匹配范围
}

func (x *ProvideConsignmentRequest) Reset() {
	*x = ProvideConsignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideConsignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideConsignmentRequest) ProtoMessage() {}

func (x *ProvideConsignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideConsignmentRequest.ProtoReflect.Descriptor instead.
func (*ProvideConsignmentRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *ProvideConsignmentRequest) GetConsignment() []byte {
	if x != nil {
		return x.Consignment
	}
	return nil
}

func (x *ProvideConsignmentRequest) GetReceiveIdHint() string {
	if x != nil {
		return x.ReceiveIdHint
	}
	return ""
}

type TransferState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiveId string `protobuf:"bytes,1,opt,name=receive_id,json=receiveId,proto3" json:"receive_id,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                  // waiting-counterparty | settled | failed | timeout
	Amount    int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                 // 结算金额（资产最小单位）
	AssetId   string `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // rgb:...
	Txid      string `protobuf:"bytes,5,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout      uint32 `protobuf:"varint,6,opt,name=vout,proto3" json:"vout,omitempty"`
}

func (x *TransferState) Reset() {
	*x = TransferState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferState) ProtoMessage() {}

func (x *TransferState) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferState.ProtoReflect.Descriptor instead.
func (*TransferState) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *TransferState) GetReceiveId() string {
	if x != nil {
		return x.ReceiveId
	}
	return ""
}

func (x *TransferState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransferState) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferState) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TransferState) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *TransferState) GetVout() uint32 {
	if x != nil {
		return x.Vout
	}
	return 0
}

type ListTransfersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol  string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	StatusFilter string `protobuf:"bytes,2,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // 空=全部
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransfersRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *ListTransfersRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListTransfersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transfers []*TransferState `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *ListTransfersResponse) GetTransfers() []*TransferState {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type ValidateConsignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Consignment           []byte   `protobuf:"bytes,1,opt,name=consignment,proto3" json:"consignment,omitempty"`
	ExpectedAmount        int64    `protobuf:"varint,2,opt,name=expected_amount,json=expectedAmount,proto3" json:"expected_amount,omitempty"`
	ExpectedRecipientSeal []byte   `protobuf:"bytes,3,opt,name=expected_recipient_seal,json=expectedRecipientSeal,proto3" json:"expected_recipient_seal,omitempty"` // 预期收款 seal（outpoint 字节）
	ExpectedClosedSeals   []string `protobuf:"bytes,4,rep,name=expected_closed_seals,json=expectedClosedSeals,proto3" json:"expected_closed_seals,omitempty"`       // 预期关闭的 seal outpoint
}

func (x *ValidateConsignmentRequest) Reset() {
	*x = ValidateConsignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateConsignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConsignmentRequest) ProtoMessage() {}

func (x *ValidateConsignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConsignmentRequest.ProtoReflect.Descriptor instead.
func (*ValidateConsignmentRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateConsignmentRequest) GetConsignment() []byte {
	if x != nil {
		return x.Consignment
	}
	return nil
}

func (x *ValidateConsignmentRequest) GetExpectedAmount() int64 {
	if x != nil {
		return x.ExpectedAmount
	}
	return 0
}

func (x *ValidateConsignmentRequest) GetExpectedRecipientSeal() []byte {
	if x != nil {
		return x.ExpectedRecipientSeal
	}
	return nil
}

func (x *ValidateConsignmentRequest) GetExpectedClosedSeals() []string {
	if x != nil {
		return x.ExpectedClosedSeals
	}
	return nil
}

type ConsignmentValidation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid         bool          `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string        `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Amount        int64         `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId       string        `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	ClosedSeals   []string      `protobuf:"bytes,5,rep,name=closed_seals,json=closedSeals,proto3" json:"closed_seals,omitempty"` // 该状态转移关闭的 seal outpoint
	OpenedSeals   []*OpenedSeal `protobuf:"bytes,6,rep,name=opened_seals,json=openedSeals,proto3" json:"opened_seals,omitempty"`
	RecipientSeal string        `protobuf:"bytes,7,opt,name=recipient_seal,json=recipientSeal,proto3" json:"recipient_seal,omitempty"` // 打开的收款 seal outpoint
	SyncedHeight  uint64        `protobuf:"varint,8,opt,name=synced_height,json=syncedHeight,proto3" json:"synced_height,omitempty"`   // 侧车索引器已同步高度（签名节点据此做高度门槛）
}

func (x *ConsignmentValidation) Reset() {
	*x = ConsignmentValidation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsignmentValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsignmentValidation) ProtoMessage() {}

func (x *ConsignmentValidation) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsignmentValidation.ProtoReflect.Descriptor instead.
func (*ConsignmentValidation) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *ConsignmentValidation) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ConsignmentValidation) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConsignmentValidation) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsignmentValidation) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ConsignmentValidation) GetClosedSeals() []string {
	if x != nil {
		return x.ClosedSeals
	}
	return nil
}

func (x *ConsignmentValidation) GetOpenedSeals() []*OpenedSeal {
	if x != nil {
		return x.OpenedSeals
	}
	return nil
}

func (x *ConsignmentValidation) GetRecipientSeal() string {
	if x != nil {
		return x.RecipientSeal
	}
	return ""
}

func (x *ConsignmentValidation) GetSyncedHeight() uint64 {
	if x != nil {
		return x.SyncedHeight
	}
	return 0
}

type OpenedSeal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outpoint string `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetId  string `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
}

func (x *OpenedSeal) Reset() {
	*x = OpenedSeal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenedSeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenedSeal) ProtoMessage() {}

func (x *OpenedSeal) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenedSeal.ProtoReflect.Descriptor instead.
func (*OpenedSeal) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *OpenedSeal) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *OpenedSeal) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OpenedSeal) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol    string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	BtcBlockHeight uint64 `protobuf:"varint,2,opt,name=btc_block_height,json=btcBlockHeight,proto3" json:"btc_block_height,omitempty"` // 可选：Go 侧已知的 BTC 高度
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *SyncRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *SyncRequest) GetBtcBlockHeight() uint64 {
	if x != nil {
		return x.BtcBlockHeight
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changed  bool     `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	NewSeals []string `protobuf:"bytes,2,rep,name=new_seals,json=newSeals,proto3" json:"new_seals,omitempty"`
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *SyncResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *SyncResponse) GetNewSeals() []string {
	if x != nil {
		return x.NewSeals
	}
	return nil
}

type ListSealsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
}

func (x *ListSealsRequest) Reset() {
	*x = ListSealsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSealsRequest) ProtoMessage() {}

func (x *ListSealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSealsRequest.ProtoReflect.Descriptor instead.
func (*ListSealsRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *ListSealsRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

type SealInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Outpoint       string `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"` // "txid:vout"
	AssetId        string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AssetSymbol    string `protobuf:"bytes,3,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Amount         int64  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                     // 资产数量（最小单位）
	BtcValue       int64  `protobuf:"varint,5,opt,name=btc_value,json=btcValue,proto3" json:"btc_value,omitempty"` // 该 UTXO 的 BTC 值（sat）
	MaturityHeight uint32 `protobuf:"varint,6,opt,name=maturity_height,json=maturityHeight,proto3" json:"maturity_height,omitempty"`
	Status         string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // pending-mint | minted | consumed
}

func (x *SealInfo) Reset() {
	*x = SealInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SealInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealInfo) ProtoMessage() {}

func (x *SealInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealInfo.ProtoReflect.Descriptor instead.
func (*SealInfo) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *SealInfo) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *SealInfo) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SealInfo) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *SealInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SealInfo) GetBtcValue() int64 {
	if x != nil {
		return x.BtcValue
	}
	return 0
}

func (x *SealInfo) GetMaturityHeight() uint32 {
	if x != nil {
		return x.MaturityHeight
	}
	return 0
}

func (x *SealInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSealsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seals []*SealInfo `protobuf:"bytes,1,rep,name=seals,proto3" json:"seals,omitempty"`
}

func (x *ListSealsResponse) Reset() {
	*x = ListSealsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSealsResponse) ProtoMessage() {}

func (x *ListSealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSealsResponse.ProtoReflect.Descriptor instead.
func (*ListSealsResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *ListSealsResponse) GetSeals() []*SealInfo {
	if x != nil {
		return x.Seals
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{14}
}

func (x *GetBalanceRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

type Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settled int64 `protobuf:"varint,1,opt,name=settled,proto3" json:"settled,omitempty"`
	Pending int64 `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (x *Balance) Reset() {
	*x = Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{15}
}

func (x *Balance) GetSettled() int64 {
	if x != nil {
		return x.Settled
	}
	return 0
}

func (x *Balance) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{16}
}

type AssetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId     string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // rgb:...
	AssetSymbol string `protobuf:"bytes,2,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	Schema      string `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"` // RGB20/IFA 等
	Precision   uint32 `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
}

func (x *AssetInfo) Reset() {
	*x = AssetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetInfo) ProtoMessage() {}

func (x *AssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetInfo.ProtoReflect.Descriptor instead.
func (*AssetInfo) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{17}
}

func (x *AssetInfo) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetInfo) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *AssetInfo) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *AssetInfo) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*AssetInfo `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{18}
}

func (x *ListAssetsResponse) GetAssets() []*AssetInfo {
	if x != nil {
		return x.Assets
	}
	return nil
}

type BuildWithdrawalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetSymbol      string `protobuf:"bytes,1,opt,name=asset_symbol,json=assetSymbol,proto3" json:"asset_symbol,omitempty"`
	AssetId          string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount           int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                            // 要发送的资产量（最小单位）
	RecipientInvoice string `protobuf:"bytes,4,opt,name=recipient_invoice,json=recipientInvoice,proto3" json:"recipient_invoice,omitempty"` // 用户 RGB 钱包生成的 invoice
	ChangeAddress    string `protobuf:"bytes,5,opt,name=change_address,json=changeAddress,proto3" json:"change_address,omitempty"`          // TSS 地址（change seal）
	FeeRate          uint32 `protobuf:"varint,6,opt,name=fee_rate,json=feeRate,proto3" json:"fee_rate,omitempty"`                           // sat/vB
}

func (x *BuildWithdrawalRequest) Reset() {
	*x = BuildWithdrawalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWithdrawalRequest) ProtoMessage() {}

func (x *BuildWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*BuildWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{19}
}

func (x *BuildWithdrawalRequest) GetAssetSymbol() string {
	if x != nil {
		return x.AssetSymbol
	}
	return ""
}

func (x *BuildWithdrawalRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *BuildWithdrawalRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BuildWithdrawalRequest) GetRecipientInvoice() string {
	if x != nil {
		return x.RecipientInvoice
	}
	return ""
}

func (x *BuildWithdrawalRequest) GetChangeAddress() string {
	if x != nil {
		return x.ChangeAddress
	}
	return ""
}

func (x *BuildWithdrawalRequest) GetFeeRate() uint32 {
	if x != nil {
		return x.FeeRate
	}
	return 0
}

type BuildWithdrawalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Psbt         []byte  `protobuf:"bytes,1,opt,name=psbt,proto3" json:"psbt,omitempty"`                                             // 未签 PSBT（TSS 将签名）
	InputAmounts []int64 `protobuf:"varint,2,rep,packed,name=input_amounts,json=inputAmounts,proto3" json:"input_amounts,omitempty"` // 各输入 prevout 值，顺序同 PSBT 输入
	Consignment  []byte  `protobuf:"bytes,3,opt,name=consignment,proto3" json:"consignment,omitempty"`                               // 该笔转移的 consignment（记录用）
}

func (x *BuildWithdrawalResponse) Reset() {
	*x = BuildWithdrawalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildWithdrawalResponse) ProtoMessage() {}

func (x *BuildWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*BuildWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{20}
}

func (x *BuildWithdrawalResponse) GetPsbt() []byte {
	if x != nil {
		return x.Psbt
	}
	return nil
}

func (x *BuildWithdrawalResponse) GetInputAmounts() []int64 {
	if x != nil {
		return x.InputAmounts
	}
	return nil
}

func (x *BuildWithdrawalResponse) GetConsignment() []byte {
	if x != nil {
		return x.Consignment
	}
	return nil
}

type FinalizeWithdrawalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PsbtSigned []byte `protobuf:"bytes,1,opt,name=psbt_signed,json=psbtSigned,proto3" json:"psbt_signed,omitempty"` // TSS 签名后的 PSBT
}

func (x *FinalizeWithdrawalRequest) Reset() {
	*x = FinalizeWithdrawalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWithdrawalRequest) ProtoMessage() {}

func (x *FinalizeWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*FinalizeWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{21}
}

func (x *FinalizeWithdrawalRequest) GetPsbtSigned() []byte {
	if x != nil {
		return x.PsbtSigned
	}
	return nil
}

type FinalizeWithdrawalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid                  string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`                                                                  // 广播用 txid；Go 侧据此做 txid↔pending 关联
	RecipientSealOutpoint string `protobuf:"bytes,2,opt,name=recipient_seal_outpoint,json=recipientSealOutpoint,proto3" json:"recipient_seal_outpoint,omitempty"` // 新打开的收款 seal
	ChangeSealOutpoint    string `protobuf:"bytes,3,opt,name=change_seal_outpoint,json=changeSealOutpoint,proto3" json:"change_seal_outpoint,omitempty"`          // change seal（可能为空）
}

func (x *FinalizeWithdrawalResponse) Reset() {
	*x = FinalizeWithdrawalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWithdrawalResponse) ProtoMessage() {}

func (x *FinalizeWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*FinalizeWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{22}
}

func (x *FinalizeWithdrawalResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *FinalizeWithdrawalResponse) GetRecipientSealOutpoint() string {
	if x != nil {
		return x.RecipientSealOutpoint
	}
	return ""
}

func (x *FinalizeWithdrawalResponse) GetChangeSealOutpoint() string {
	if x != nil {
		return x.ChangeSealOutpoint
	}
	return ""
}

type ParseBtcTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BtcTx       []byte `protobuf:"bytes,1,opt,name=btc_tx,json=btcTx,proto3" json:"btc_tx,omitempty"`                     // 序列化 BTC 交易（no-witness）
	TssPkScript []byte `protobuf:"bytes,2,opt,name=tss_pk_script,json=tssPkScript,proto3" json:"tss_pk_script,omitempty"` // TSS 脚本，用于定位 seal 输出
}

func (x *ParseBtcTxRequest) Reset() {
	*x = ParseBtcTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseBtcTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseBtcTxRequest) ProtoMessage() {}

func (x *ParseBtcTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseBtcTxRequest.ProtoReflect.Descriptor instead.
func (*ParseBtcTxRequest) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{23}
}

func (x *ParseBtcTxRequest) GetBtcTx() []byte {
	if x != nil {
		return x.BtcTx
	}
	return nil
}

func (x *ParseBtcTxRequest) GetTssPkScript() []byte {
	if x != nil {
		return x.TssPkScript
	}
	return nil
}

type ParseBtcTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasRgbCommitment bool   `protobuf:"varint,1,opt,name=has_rgb_commitment,json=hasRgbCommitment,proto3" json:"has_rgb_commitment,omitempty"`
	CommitmentType   string `protobuf:"bytes,2,opt,name=commitment_type,json=commitmentType,proto3" json:"commitment_type,omitempty"` // "opret" | "tapret" | ""
	AssetId          string `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SealOutputIndex  uint32 `protobuf:"varint,4,opt,name=seal_output_index,json=sealOutputIndex,proto3" json:"seal_output_index,omitempty"`
}

func (x *ParseBtcTxResponse) Reset() {
	*x = ParseBtcTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rgb_sidecar_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseBtcTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseBtcTxResponse) ProtoMessage() {}

func (x *ParseBtcTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rgb_sidecar_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseBtcTxResponse.ProtoReflect.Descriptor instead.
func (*ParseBtcTxResponse) Descriptor() ([]byte, []int) {
	return file_rgb_sidecar_proto_rawDescGZIP(), []int{24}
}

func (x *ParseBtcTxResponse) GetHasRgbCommitment() bool {
	if x != nil {
		return x.HasRgbCommitment
	}
	return false
}

func (x *ParseBtcTxResponse) GetCommitmentType() string {
	if x != nil {
		return x.CommitmentType
	}
	return ""
}

func (x *ParseBtcTxResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ParseBtcTxResponse) GetSealOutputIndex() uint32 {
	if x != nil {
		return x.SealOutputIndex
	}
	return 0
}

var File_rgb_sidecar_proto protoreflect.FileDescriptor

var file_rgb_sidecar_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x22, 0xaf, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x13, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x12, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x10, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x67, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x61, 0x6c, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x65, 0x0a, 0x19, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x64, 0x48, 0x69,
	0x6e, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x76, 0x6f, 0x75, 0x74, 0x22, 0x5e, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x51, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x22, 0xd3, 0x01, 0x0a, 0x1a, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x17, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x15, 0x65,
	0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x5f, 0x73,
	0x65, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x22,
	0xb0, 0x02, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x5f, 0x73, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x6f, 0x70,
	0x65, 0x6e, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x61, 0x6c, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x61, 0x6c, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x6e, 0x65,
	0x64, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x6c, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x5b, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x61, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x22,
	0x5a, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x74, 0x63, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x62, 0x74, 0x63,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x45, 0x0a, 0x0c, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x61,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x61,
	0x6c, 0x73, 0x22, 0x35, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xda, 0x01, 0x0a, 0x08, 0x53, 0x65,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x74, 0x63, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x74, 0x63,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x61, 0x74, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x6d, 0x61, 0x74, 0x75, 0x72, 0x69, 0x74, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x40, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65,
	0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x73,
	0x65, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x67, 0x62,
	0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x73, 0x65, 0x61, 0x6c, 0x73, 0x22, 0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x22, 0x3d, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22,
	0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x7f, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x67,
	0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0xdd, 0x01, 0x0a, 0x16,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x11,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0x74, 0x0a, 0x17, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x73, 0x62, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x73, 0x62, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0c, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x3c, 0x0a, 0x19, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x73, 0x62, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x73, 0x62, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x22,
	0x9a, 0x01, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78,
	0x69, 0x64, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x73, 0x65, 0x61, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x15, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65,
	0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x65, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x11,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x74, 0x63, 0x5f, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x62, 0x74, 0x63, 0x54, 0x78, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x73, 0x73, 0x5f,
	0x70, 0x6b, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x74, 0x73, 0x73, 0x50, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0xb2, 0x01, 0x0a,
	0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x68, 0x61, 0x73, 0x5f, 0x72, 0x67, 0x62, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x68, 0x61, 0x73, 0x52, 0x67, 0x62, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x61, 0x6c, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0f, 0x73, 0x65, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x32, 0xa0, 0x07, 0x0a, 0x0a, 0x52, 0x67, 0x62, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x12, 0x21, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x58,
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72,
	0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x56, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x12, 0x21, 0x2e, 0x72, 0x67, 0x62, 0x5f,
	0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x72,
	0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x62, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69,
	0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x18, 0x2e, 0x72,
	0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64,
	0x65, 0x63, 0x61, 0x72, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x12, 0x1d,
	0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x53, 0x65, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x53, 0x65, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x2e, 0x72, 0x67,
	0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x67,
	0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12,
	0x1e, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5c, 0x0a, 0x0f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61,
	0x72, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73,
	0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65,
	0x0a, 0x12, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x61, 0x6c, 0x12, 0x26, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72,
	0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x74,
	0x63, 0x54, 0x78, 0x12, 0x1e, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61,
	0x72, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x67, 0x62, 0x5f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61,
	0x72, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x74, 0x63, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x33, 0x33, 0x63, 0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x69, 0x6e, 0x6f, 0x2f,
	0x72, 0x67, 0x62, 0x32, 0x30, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rgb_sidecar_proto_rawDescOnce sync.Once
	file_rgb_sidecar_proto_rawDescData = file_rgb_sidecar_proto_rawDesc
)

func file_rgb_sidecar_proto_rawDescGZIP() []byte {
	file_rgb_sidecar_proto_rawDescOnce.Do(func() {
		file_rgb_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(file_rgb_sidecar_proto_rawDescData)
	})
	return file_rgb_sidecar_proto_rawDescData
}

var file_rgb_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rgb_sidecar_proto_goTypes = []interface{}{
	(*CreateReceiveRequest)(nil),       // 0: rgb_sidecar.CreateReceiveRequest
	(*ReceiveData)(nil),                // 1: rgb_sidecar.ReceiveData
	(*ProvideConsignmentRequest)(nil),  // 2: rgb_sidecar.ProvideConsignmentRequest
	(*TransferState)(nil),              // 3: rgb_sidecar.TransferState
	(*ListTransfersRequest)(nil),       // 4: rgb_sidecar.ListTransfersRequest
	(*ListTransfersResponse)(nil),      // 5: rgb_sidecar.ListTransfersResponse
	(*ValidateConsignmentRequest)(nil), // 6: rgb_sidecar.ValidateConsignmentRequest
	(*ConsignmentValidation)(nil),      // 7: rgb_sidecar.ConsignmentValidation
	(*OpenedSeal)(nil),                 // 8: rgb_sidecar.OpenedSeal
	(*SyncRequest)(nil),                // 9: rgb_sidecar.SyncRequest
	(*SyncResponse)(nil),               // 10: rgb_sidecar.SyncResponse
	(*ListSealsRequest)(nil),           // 11: rgb_sidecar.ListSealsRequest
	(*SealInfo)(nil),                   // 12: rgb_sidecar.SealInfo
	(*ListSealsResponse)(nil),          // 13: rgb_sidecar.ListSealsResponse
	(*GetBalanceRequest)(nil),          // 14: rgb_sidecar.GetBalanceRequest
	(*Balance)(nil),                    // 15: rgb_sidecar.Balance
	(*ListAssetsRequest)(nil),          // 16: rgb_sidecar.ListAssetsRequest
	(*AssetInfo)(nil),                  // 17: rgb_sidecar.AssetInfo
	(*ListAssetsResponse)(nil),         // 18: rgb_sidecar.ListAssetsResponse
	(*BuildWithdrawalRequest)(nil),     // 19: rgb_sidecar.BuildWithdrawalRequest
	(*BuildWithdrawalResponse)(nil),    // 20: rgb_sidecar.BuildWithdrawalResponse
	(*FinalizeWithdrawalRequest)(nil),  // 21: rgb_sidecar.FinalizeWithdrawalRequest
	(*FinalizeWithdrawalResponse)(nil), // 22: rgb_sidecar.FinalizeWithdrawalResponse
	(*ParseBtcTxRequest)(nil),          // 23: rgb_sidecar.ParseBtcTxRequest
	(*ParseBtcTxResponse)(nil),         // 24: rgb_sidecar.ParseBtcTxResponse
}
var file_rgb_sidecar_proto_depIdxs = []int32{
	3,  // 0: rgb_sidecar.ListTransfersResponse.transfers:type_name -> rgb_sidecar.TransferState
	8,  // 1: rgb_sidecar.ConsignmentValidation.opened_seals:type_name -> rgb_sidecar.OpenedSeal
	12, // 2: rgb_sidecar.ListSealsResponse.seals:type_name -> rgb_sidecar.SealInfo
	17, // 3: rgb_sidecar.ListAssetsResponse.assets:type_name -> rgb_sidecar.AssetInfo
	0,  // 4: rgb_sidecar.RgbSidecar.CreateReceive:input_type -> rgb_sidecar.CreateReceiveRequest
	2,  // 5: rgb_sidecar.RgbSidecar.ProvideConsignment:input_type -> rgb_sidecar.ProvideConsignmentRequest
	4,  // 6: rgb_sidecar.RgbSidecar.ListTransfers:input_type -> rgb_sidecar.ListTransfersRequest
	6,  // 7: rgb_sidecar.RgbSidecar.ValidateConsignment:input_type -> rgb_sidecar.ValidateConsignmentRequest
	9,  // 8: rgb_sidecar.RgbSidecar.Sync:input_type -> rgb_sidecar.SyncRequest
	11, // 9: rgb_sidecar.RgbSidecar.ListSeals:input_type -> rgb_sidecar.ListSealsRequest
	14, // 10: rgb_sidecar.RgbSidecar.GetBalance:input_type -> rgb_sidecar.GetBalanceRequest
	16, // 11: rgb_sidecar.RgbSidecar.ListAssets:input_type -> rgb_sidecar.ListAssetsRequest
	19, // 12: rgb_sidecar.RgbSidecar.BuildWithdrawal:input_type -> rgb_sidecar.BuildWithdrawalRequest
	21, // 13: rgb_sidecar.RgbSidecar.FinalizeWithdrawal:input_type -> rgb_sidecar.FinalizeWithdrawalRequest
	23, // 14: rgb_sidecar.RgbSidecar.ParseBtcTx:input_type -> rgb_sidecar.ParseBtcTxRequest
	1,  // 15: rgb_sidecar.RgbSidecar.CreateReceive:output_type -> rgb_sidecar.ReceiveData
	3,  // 16: rgb_sidecar.RgbSidecar.ProvideConsignment:output_type -> rgb_sidecar.TransferState
	5,  // 17: rgb_sidecar.RgbSidecar.ListTransfers:output_type -> rgb_sidecar.ListTransfersResponse
	7,  // 18: rgb_sidecar.RgbSidecar.ValidateConsignment:output_type -> rgb_sidecar.ConsignmentValidation
	10, // 19: rgb_sidecar.RgbSidecar.Sync:output_type -> rgb_sidecar.SyncResponse
	13, // 20: rgb_sidecar.RgbSidecar.ListSeals:output_type -> rgb_sidecar.ListSealsResponse
	15, // 21: rgb_sidecar.RgbSidecar.GetBalance:output_type -> rgb_sidecar.Balance
	18, // 22: rgb_sidecar.RgbSidecar.ListAssets:output_type -> rgb_sidecar.ListAssetsResponse
	20, // 23: rgb_sidecar.RgbSidecar.BuildWithdrawal:output_type -> rgb_sidecar.BuildWithdrawalResponse
	22, // 24: rgb_sidecar.RgbSidecar.FinalizeWithdrawal:output_type -> rgb_sidecar.FinalizeWithdrawalResponse
	24, // 25: rgb_sidecar.RgbSidecar.ParseBtcTx:output_type -> rgb_sidecar.ParseBtcTxResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rgb_sidecar_proto_init() }
func file_rgb_sidecar_proto_init() {
	if File_rgb_sidecar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rgb_sidecar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReceiveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvideConsignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTransfersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTransfersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateConsignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsignmentValidation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenedSeal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSealsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SealInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSealsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildWithdrawalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildWithdrawalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeWithdrawalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeWithdrawalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseBtcTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rgb_sidecar_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseBtcTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rgb_sidecar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rgb_sidecar_proto_goTypes,
		DependencyIndexes: file_rgb_sidecar_proto_depIdxs,
		MessageInfos:      file_rgb_sidecar_proto_msgTypes,
	}.Build()
	File_rgb_sidecar_proto = out.File
	file_rgb_sidecar_proto_rawDesc = nil
	file_rgb_sidecar_proto_goTypes = nil
	file_rgb_sidecar_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RgbSidecarClient is the client API for RgbSidecar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RgbSidecarClient interface {
	// ---- 充值 ----
	CreateReceive(ctx context.Context, in *CreateReceiveRequest, opts ...grpc.CallOption) (*ReceiveData, error)
	ProvideConsignment(ctx context.Context, in *ProvideConsignmentRequest, opts ...grpc.CallOption) (*TransferState, error)
	ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	// ---- 只读校验（签名节点用，确定性、与钱包状态无关性由实现保证并返回 synced_height）----
	ValidateConsignment(ctx context.Context, in *ValidateConsignmentRequest, opts ...grpc.CallOption) (*ConsignmentValidation, error)
	// ---- 查询 ----
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	ListSeals(ctx context.Context, in *ListSealsRequest, opts ...grpc.CallOption) (*ListSealsResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*Balance, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error)
	// ---- 提现 ----
	BuildWithdrawal(ctx context.Context, in *BuildWithdrawalRequest, opts ...grpc.CallOption) (*BuildWithdrawalResponse, error)
	FinalizeWithdrawal(ctx context.Context, in *FinalizeWithdrawalRequest, opts ...grpc.CallOption) (*FinalizeWithdrawalResponse, error)
	// ---- 辅助 ----
	ParseBtcTx(ctx context.Context, in *ParseBtcTxRequest, opts ...grpc.CallOption) (*ParseBtcTxResponse, error)
}

type rgbSidecarClient struct {
	cc grpc.ClientConnInterface
}

func NewRgbSidecarClient(cc grpc.ClientConnInterface) RgbSidecarClient {
	return &rgbSidecarClient{cc}
}

func (c *rgbSidecarClient) CreateReceive(ctx context.Context, in *CreateReceiveRequest, opts ...grpc.CallOption) (*ReceiveData, error) {
	out := new(ReceiveData)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/CreateReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ProvideConsignment(ctx context.Context, in *ProvideConsignmentRequest, opts ...grpc.CallOption) (*TransferState, error) {
	out := new(TransferState)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ProvideConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ListTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ValidateConsignment(ctx context.Context, in *ValidateConsignmentRequest, opts ...grpc.CallOption) (*ConsignmentValidation, error) {
	out := new(ConsignmentValidation)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ValidateConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ListSeals(ctx context.Context, in *ListSealsRequest, opts ...grpc.CallOption) (*ListSealsResponse, error) {
	out := new(ListSealsResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ListSeals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*Balance, error) {
	out := new(Balance)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	out := new(ListAssetsResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ListAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) BuildWithdrawal(ctx context.Context, in *BuildWithdrawalRequest, opts ...grpc.CallOption) (*BuildWithdrawalResponse, error) {
	out := new(BuildWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/BuildWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) FinalizeWithdrawal(ctx context.Context, in *FinalizeWithdrawalRequest, opts ...grpc.CallOption) (*FinalizeWithdrawalResponse, error) {
	out := new(FinalizeWithdrawalResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/FinalizeWithdrawal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rgbSidecarClient) ParseBtcTx(ctx context.Context, in *ParseBtcTxRequest, opts ...grpc.CallOption) (*ParseBtcTxResponse, error) {
	out := new(ParseBtcTxResponse)
	err := c.cc.Invoke(ctx, "/rgb_sidecar.RgbSidecar/ParseBtcTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RgbSidecarServer is the server API for RgbSidecar service.
type RgbSidecarServer interface {
	// ---- 充值 ----
	CreateReceive(context.Context, *CreateReceiveRequest) (*ReceiveData, error)
	ProvideConsignment(context.Context, *ProvideConsignmentRequest) (*TransferState, error)
	ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error)
	// ---- 只读校验（签名节点用，确定性、与钱包状态无关性由实现保证并返回 synced_height）----
	ValidateConsignment(context.Context, *ValidateConsignmentRequest) (*ConsignmentValidation, error)
	// ---- 查询 ----
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	ListSeals(context.Context, *ListSealsRequest) (*ListSealsResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*Balance, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error)
	// ---- 提现 ----
	BuildWithdrawal(context.Context, *BuildWithdrawalRequest) (*BuildWithdrawalResponse, error)
	FinalizeWithdrawal(context.Context, *FinalizeWithdrawalRequest) (*FinalizeWithdrawalResponse, error)
	// ---- 辅助 ----
	ParseBtcTx(context.Context, *ParseBtcTxRequest) (*ParseBtcTxResponse, error)
}

// UnimplementedRgbSidecarServer can be embedded to have forward compatible implementations.
type UnimplementedRgbSidecarServer struct {
}

func (*UnimplementedRgbSidecarServer) CreateReceive(context.Context, *CreateReceiveRequest) (*ReceiveData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceive not implemented")
}
func (*UnimplementedRgbSidecarServer) ProvideConsignment(context.Context, *ProvideConsignmentRequest) (*TransferState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvideConsignment not implemented")
}
func (*UnimplementedRgbSidecarServer) ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransfers not implemented")
}
func (*UnimplementedRgbSidecarServer) ValidateConsignment(context.Context, *ValidateConsignmentRequest) (*ConsignmentValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConsignment not implemented")
}
func (*UnimplementedRgbSidecarServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedRgbSidecarServer) ListSeals(context.Context, *ListSealsRequest) (*ListSealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSeals not implemented")
}
func (*UnimplementedRgbSidecarServer) GetBalance(context.Context, *GetBalanceRequest) (*Balance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedRgbSidecarServer) ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssets not implemented")
}
func (*UnimplementedRgbSidecarServer) BuildWithdrawal(context.Context, *BuildWithdrawalRequest) (*BuildWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildWithdrawal not implemented")
}
func (*UnimplementedRgbSidecarServer) FinalizeWithdrawal(context.Context, *FinalizeWithdrawalRequest) (*FinalizeWithdrawalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeWithdrawal not implemented")
}
func (*UnimplementedRgbSidecarServer) ParseBtcTx(context.Context, *ParseBtcTxRequest) (*ParseBtcTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseBtcTx not implemented")
}

func RegisterRgbSidecarServer(s *grpc.Server, srv RgbSidecarServer) {
	s.RegisterService(&_RgbSidecar_serviceDesc, srv)
}

func _RgbSidecar_CreateReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).CreateReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/CreateReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).CreateReceive(ctx, req.(*CreateReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ProvideConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideConsignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ProvideConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ProvideConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ProvideConsignment(ctx, req.(*ProvideConsignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ListTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ListTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ListTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ListTransfers(ctx, req.(*ListTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ValidateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConsignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ValidateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ValidateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ValidateConsignment(ctx, req.(*ValidateConsignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ListSeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ListSeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ListSeals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ListSeals(ctx, req.(*ListSealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ListAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ListAssets(ctx, req.(*ListAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_BuildWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).BuildWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/BuildWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).BuildWithdrawal(ctx, req.(*BuildWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_FinalizeWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).FinalizeWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/FinalizeWithdrawal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).FinalizeWithdrawal(ctx, req.(*FinalizeWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RgbSidecar_ParseBtcTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseBtcTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RgbSidecarServer).ParseBtcTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rgb_sidecar.RgbSidecar/ParseBtcTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RgbSidecarServer).ParseBtcTx(ctx, req.(*ParseBtcTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RgbSidecar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rgb_sidecar.RgbSidecar",
	HandlerType: (*RgbSidecarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReceive",
			Handler:    _RgbSidecar_CreateReceive_Handler,
		},
		{
			MethodName: "ProvideConsignment",
			Handler:    _RgbSidecar_ProvideConsignment_Handler,
		},
		{
			MethodName: "ListTransfers",
			Handler:    _RgbSidecar_ListTransfers_Handler,
		},
		{
			MethodName: "ValidateConsignment",
			Handler:    _RgbSidecar_ValidateConsignment_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _RgbSidecar_Sync_Handler,
		},
		{
			MethodName: "ListSeals",
			Handler:    _RgbSidecar_ListSeals_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _RgbSidecar_GetBalance_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _RgbSidecar_ListAssets_Handler,
		},
		{
			MethodName: "BuildWithdrawal",
			Handler:    _RgbSidecar_BuildWithdrawal_Handler,
		},
		{
			MethodName: "FinalizeWithdrawal",
			Handler:    _RgbSidecar_FinalizeWithdrawal_Handler,
		},
		{
			MethodName: "ParseBtcTx",
			Handler:    _RgbSidecar_ParseBtcTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rgb_sidecar.proto",
}
