#chain33的客户端文件
cliCmd = "./chain33-cli"
#CSV文件
csv = "test.csv"
#发送一笔交易后等待回执的超时时间，单位秒
checkTimeout = 30
#发送地址
fromAddr = "12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
#发送地址私钥
fromPri = "4257D8692EF7FE13C68B65D6A52F03933DB2FA5CE8FAF210B5B8B80C721CED01"
#每笔交易发送间隔时间，单位ms
interval = 100
#CSV标题头行数
csvTitleLine = 1
